package fixture

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// SessionManifest records a multi-stream capture session (e.g. InterleaveTest)
// where two PLC programs are captured concurrently into separate fixture files.
type SessionManifest struct {
	// CapturedAt is the UTC start time of the session in RFC 3339 format.
	CapturedAt string `yaml:"captured_at"`

	// ProgramDir is the name of the fixture directory under testdata/fixtures/
	// (e.g. "InterleaveTest").
	ProgramDir string `yaml:"program_dir"`

	// Streams lists each individual stream captured during this session.
	Streams []StreamRef `yaml:"streams"`
}

// StreamRef identifies one captured stream within a SessionManifest.
type StreamRef struct {
	// BaseTopic is the MQTT base topic used during capture (e.g. "Devices/ConveyorB").
	BaseTopic string `yaml:"base_topic"`

	// PLCLabel is the human-readable label for the PLC (e.g. "PLC 1").
	PLCLabel string `yaml:"plc_label"`

	// FixtureFile is the path to the symbols/message-*.yml sidecar for this stream,
	// relative to the session manifest file's directory (i.e. relative to capturesDir).
	FixtureFile string `yaml:"fixture_file"`
}

const sessionManifestHeader = `# Auto-generated by cmd/runner — records a multi-stream capture session.
# Each stream entry references the symbols/message-*.yml sidecar for one PLC program.

`

// WriteSession writes a SessionManifest to a YAML file at path.
func WriteSession(path string, m *SessionManifest) error {
	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("fixture: yaml marshal session manifest: %w", err)
	}
	content := []byte(sessionManifestHeader)
	content = append(content, data...)
	return os.WriteFile(path, content, 0644)
}

// LoadSession reads a SessionManifest from the YAML file at path.
func LoadSession(path string) (*SessionManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("fixture: read session manifest %s: %w", path, err)
	}
	var m SessionManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("fixture: yaml unmarshal session manifest %s: %w", path, err)
	}
	return &m, nil
}
